FROM fedora:25

MAINTAINER salviof@gmail.com coletivojava.com.br

RUN rpm -ivh https://dev.mysql.com/get/mysql57-community-release-fc25-9.noarch.rpm && \
    dnf -y install mysql-utilities
RUN dnf install git -y
COPY instalacao.sh ~/instalacao.sh

RUN  mkdir /home/superBits/devTools/ -s
RUN  git clone https://github.com/salviof/DBDiff.git
RUN mv ./DBDiff -r -f
RUN  sudo chmod +x ~/instalacao.sh
